# Define the Firmware Version Number
export PRJ_VERSION = 0x00000001

# Define target output
target: dcp

# Define target part
export PRJ_PART = xcvu9p-flgc2104-1-e

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
