export GIT_BYPASS = 1

# Define the Firmware Version Number
export PRJ_VERSION = 0x00000001

# Define target output
target: dcp

# Define target part
export PRJ_PART = XC7Z045FFG900-2

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
